export const mockSelectedUser = {
    key: 0,
    id: 1,
    login: 'testUserLogin',
    avatar_url: 'testUseravatarUrl',
    events_url: 'testUsereventsUrl',
    followers_url: 'testUserfollowersUrl',
    following_url: 'testUserfollowingUrl',
    gists_url: 'testUsergistsUrl',
    gravatar_id: 'testUsergravatarId',
    html_url: 'testUserhtmlUrl',
    node_id: 'testUsernodeId',
    organizations_url: 'testUserorganizations',
    received_events_url: 'testUserreceivedEvents',
    repos_url: 'testUserrepos',
    score: 2,
    site_admin: false,
    starred_url: 'testUserstarred',
    subscriptions_url: 'testUsersubscriptions',
    type: 'testUsertype',
    url: 'https://api.github.com/users/Kwynto',
};
